kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  scheduler:
    extraArgs:
      "feature-gates": "NonPreemptingPriority=true"
